### ISSUE TITLE
SSL verify issues in certain cases

### ISSUE THREAD

**Issue by warmstarter** [warmstarter/tinyfugue#35]
python-scripting branch is failing on one site, this is either because it is not a self-signed cert or something with PennMUSH, check into it.

**Comment by warmstarter** [comment]
I thought this issue was only in python-scripting branch, but I appear to be wrong.
SSL verify works in some cases.

First it tries to connect via IPv6 and gets:
```SSL: cert verify error: err=20 'unable to get local issuer certificate' depth:0 cn:
Intermediate connection to MUSHNAME failed: SSL/lib: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed```

then it tries again via IPv4 and gets:

```Connection to MUSHNAME failed: SSL/system: Operation now in progress```

It never connects. This is with ssl_continue on.

On another game with a self-signed certificate and a hostname mismatch I get this:

```% SSL: cert verify error: err=18 'self signed certificate' depth:0 cn:/CN=example.com
% SSL: cert verify error: err=62 'Hostname mismatch' depth:0 cn:/CN=example.com
% SSL: chain: depth:0 cn:/CN=example.com
% SSL: cert verify failed: ERROR err=62```

and yet it happily connects whether ssl_continue is on or off.

Something's a bit funky here.

**Comment by nnasteff1** [comment]
Having similar issues myself. I'm actually getting the same exact error I would get when trying to connect to my main MUD, Dune (dunemud.net 6788) with the Rebirth build:
```
% Trying to connect to unnamed9: 68.183.23.43 6788.
% SSL: cert verify depth exceeded: allowed=0 actual=2
% SSL: cert verify error: err=22 'certificate chain too long' depth:2 cn:/
    C=US/O=Internet Security Research Group/CN=ISRG Root X1
% Connection to unnamed9 failed: SSL/lib: error:1416F086:SSL
    routines:tls_process_server_certificate:certificate verify failed
```
Tested another random MUD with SSL, and I get the same error attempting to connect to Shadowgate (shadowgate.org 8443). 

Also, when I try to connect to PennMUSH, I get:
```
`% Trying to connect to unnamed8: 23.253.78.117 4201.
% Intermediate connection to unnamed8 failed: SSL/lib: error:1408F10B:SSL
    routines:ssl3_get_record:wrong version number
% Trying to connect to unnamed8: 2001:4800:7817:101:be76:4eff:fe04:35ae 4201.
% Connection to unnamed8 failed: 2001:4800:7817:101:be76:4eff:fe04:35ae 4201:
    Network is unreachable
```

This was duplicated on my main machine and a fresh install, both Raspbian Buster 10 (using libssl-dev)

~~EDIT: Forgot to specify, this occurs on the python-scripting branch~~
EDIT2: I'm receiving the same errors on both pre-release and python-scripting branches.

**Comment by warmstarter** [comment]
fixed in python-scripting, to be merged into pre-release shortly.
